repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: pnpm run lint
        language: system
        pass_filenames: false
      - id: typecheck
        name: typecheck
        entry: pnpm run typecheck
        language: system
        pass_filenames: false
