services:
  api:
    build: .
    image: aws-edge-backend-starter:dev
    ports:
      - "3000:3000"
    env_file: .env
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
