name: IaC
on:
  push:
    paths:
      - 'infra/**'
  pull_request:
    paths:
      - 'infra/**'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - run: terraform -chdir=infra/terraform fmt -check
      - run: terraform -chdir=infra/terraform init -backend=false
      - run: terraform -chdir=infra/terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.7
        with:
          working_directory: infra/terraform
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform
